language: cpp
before_install:
    - sudo add-apt-repository --yes ppa:codegear/release
    - sudo apt-get update -qq
install:
    - sudo apt-get install --force-yes make premake4
compiler:
    - clang
    - gcc
script: 
    - premake4 gmake
    - make
