language: cpp

compiler:
    - clang
    # - gcc

before_install:
# premake4
    - sudo add-apt-repository --yes ppa:codegear/release

# gcc 4.8
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

# clang 3.4
    - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi

    - sudo apt-get update -qq

env:
    CFLAGS=-I/usr/local/include
    LDFLAGS=-L/usr/local/lib

install:
    - sudo apt-get install --force-yes make premake4

# gcc 4.8
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated clang-3.4; fi
    # - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c+11 -stdlib=libc++"; fi
    - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi

# clang 3.4 libc++
    - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
    - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
    - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
    - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
    - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

before_script:
    - sudo apt-get update

    # boost
    - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
    - tar --bzip2 -xf boost_1_55_0.tar.bz2
    - cd boost_1_55_0
    - ./bootstrap.sh --help
    # We only need thread (and also only header-only).
    # All the rest takes way too much time to compile.
    - sudo ./bootstrap.sh --with-libraries="thread"
    # Way too much output, so just display the last 50 lines.
    - sudo ./b2 install | tail -n 50
    - cd ..

script: 
    - $CXX --version
    - premake4 gmake
    - make -e
    - if [ -e "./bin/release/ostests_d" ]; then ./bin/release/ostests_d; fi
